### ISSUE TITLE
It can't find/download the latest munit stable version

### ISSUE THREAD

**Issue by naferx** [scalameta/maven-scala-seed.g8#13]
```
> $ g8 --version
g8 0.16.2

> $ g8 scalameta/maven-scala-seed.g8

Could not find latest stable version at https://search.maven.org/solrsearch/select?q=g:%22org.scalameta%22+AND+a:%22munit_2.13%22&rows=10&wt=xml&core=gav
```

I checked the URL via web browser and it returns an XML doc. 

If this is a valid issue and you can point out the correct place to check I'd submit a PR

**Comment by tgodzik** [comment]
Should be fixed now, seems munit has 10 last versions being milestones and since we were looking for latests stable plus the limit of the search is last 10, it failed.

Tested it and it should work.

**Comment by naferx** [comment]
it did work. thanks
